application: serieslycom
version: 2-5
runtime: python
api_version: 1

default_expiration: '3650d'

inbound_services:
- xmpp_message

derived_file_type:
- python_precompiled

error_handlers:
  - file: templates/error.html
  - error_code: dos_api_denial
    file: templates/error_dos.html
  - error_code: over_quota
    file: templates/error_quota.html
  - error_code: timeout
    file: templates/error_timeout.html

handlers:
- url: /favicon.ico
  static_files: media/img/favicon.ico
  upload: media/img/favicon.ico

- url: /robots.txt
  static_files: media/robots.txt
  upload: media/robots.txt
  
- url: /apple-touch-icon.png
  static_files: media/img/apple-touch-icon.png
  upload: media/img/apple-touch-icon.png
  
- url: /media
  static_dir: media
  
- url: /seriesly-remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  
- url: /shows/clear/cache/
  script: main.py
  login: admin

- url: /shows/import_show/
  script: main.py
  login: admin
  
- url: /shows/update/
  script: main.py
  login: admin

- url: /subscriptions/mail-task/
  script: main.py
  login: admin

- url: /subscriptions/xmpp-task/
  script: main.py
  login: admin

- url: /subscriptions/webhook-task/
  script: main.py
  login: admin

- url: /statistics/.*
  script: main.py
  login: admin

- url: /.*
  script: main.py
